### ISSUE TITLE
Base note not the same as seen on keyboard map

### ISSUE THREAD

**Issue by julianmusic** [SeanArchibald/scale-workshop#106]
Hello Sevish, 

Thx for your Scale Workshop system.
I´ve been trying it out for hours now and did not find a solution for my problem.
I would like to create a F#maj just intonation 432hz .tun file. - Here is my reference scale sheet: https://432hertz.de/45-hz-gb-chromatic/ 
Everytime I set up the base note to F# (45hz, 90hz, 180hz or etc.) it jumps to the keyboard note A on Scale Workshop (attached photo). 

<img width="1672" alt="F#maj just intonation 432hz" src="https://user-images.githubusercontent.com/73550850/97340458-1743c880-1884-11eb-9614-d47e91b1be2b.png">

Is this a bug or am I doing something wrong?

Would be very grateful for your help.
All the best, Julian

**Comment by vsicurella** [comment]
Hi Julian, thanks for your input, I think it does reveal there could be an improvement. It appears the tuning is working correctly for me, and it should save the tuning file correctly, but the graphics appear to always use the "A" key as 1/1. This is because the color pattern is different from the Base MIDI note control, and you can create your own custom patterns in the "Isomorphic Keyboard Settings" section. If you wrote the pattern out to start on the F# key, it would look correct.

Also as a side note, I think it's fine to do it the way you are doing, but you can also keep the reference closer to A4 (Midi Note 69), by using Base Frequency 360 and F#4 or Midi Note 66.

**Comment by julianmusic** [comment]
Hi Vsicurella, thank you very much for your reply. - Got it - Really helpful!!!
