### ISSUE TITLE
Scale Workshop ignored edited descriptions in Scala file exports

### ISSUE THREAD

**Issue by jimbla** [SeanArchibald/scale-workshop#25]
Scale Workshop just ignored 20 files worth of painstakingly written descriptions in the Scala file exports. I made an equal temperament first, then chose a mode, then edited the description before exporting as a Scala file. All the files had the description from the equal tempered I created first, but not the descriptions I edited them to have later.

**Comment by SeanArchibald** [comment]
will look into it. thanks for reporting.

just to confirm, did you hit the 'calculate' button after changing the description and before exporting?

**Comment by SeanArchibald** [comment]
I'm going to assume that the 'Calculate' button was NOT pressed between changing the description and before exporting. Because why would anybody do that? That would be unintuitive.

But how Scale Workshop actually works (for now) is that the file exports are all done at the earlier moment when the tuning was 'Calculate'd... the exports are not ran when you click the export button. So unless you have just clicked the 'Calculate' button, there may be changes that won't show up in your exports.

In my opinion, this is the weirdest and most unintuitive aspect of using Scale Workshop. And it will be fixed! But it will require refactoring and rethinking how data flows within the app, and that will take some time.

@jimbla in the meantime please give the 'Calculate' button one click before exporting what you're working on

**Comment by SeanArchibald** [comment]
This issue should now be fixed in version 0.8.9. Let me know if you get any similar issues from now on
