### ISSUE TITLE
Default value for generators up down

### ISSUE THREAD

**Issue by jimbla** [SeanArchibald/scale-workshop#58]
I am not happy with the "generators up and down" buttons in the rank2 dialog window. Often times they are set to some random up and down value and I have to manually click it all the way up to a normal chain of only positive generators. I think it would be best if an only positive chain was the default.

**Comment by SeanArchibald** [comment]
My approach was to set the defaults to something that newbies could play with and figure out how it works (currently it makes a 7 note Pythagorean major scale). That might not be the best long term solution as returning users like yourself might want it to default to only positive generators. I'm not sure yet because the only feedback I had about rank-2 generation so far is this issue.

**Comment by jimbla** [comment]
If it confuses me, it might confuse newbies too, ha ha. I understand the teaching aspect, but most newbies tend to use only positive chains anyway. At least it should be set to only positive if you set the generator to something else than 3/2, because having it 7 up or 5 down or whatever is the default now for all rank2 scales is madness. It is bound to confuse newbies ending up with rotations that they didn't have in mind. Thanks for implementing it anyway...

**Comment by SeanArchibald** [comment]
now fixed in master branch. give it a try @jimbla as it now defaults to positive generators only
