### ISSUE TITLE
Base note shift not reflected in Note table

### ISSUE THREAD

**Issue by daslicht** [SeanArchibald/scale-workshop#98]
Hi,
when shifting the basenote from lets say a to c, c shoudl be triggerner in teh table when playing c on a keyboard and not a.
![](https://i.imgur.com/keRXJaX.png)

**Comment by vsicurella** [comment]
Thanks for your input! I don't think this is actually broken, but you raise a good point for usability. The reason it still plays "A" is because you also have to switch the "Base frequency" above that field. The "Auto" button takes care of that for you, but that's not evident (and I wasn't even sure if that's what it would do when I started writing this).
I think it would be good to rename and/or move the button to make that more clear. Alternatively instead of a button, there could be a standard midi note menu that has note & octave names like C3, A4, D5, etc that automatically select both the "Base Freq" and "Base Note".

**Comment by vsicurella** [comment]
actually with a closer look, even if you set the base frequency to something, it doesn't always seem to update when it should!

**Comment by daslicht** [comment]
Yeh, the playing sound playing is fine , the visualization is just wrong.

**Comment by meszaros-lajos-gyorgy** [comment]
The issue comes from the fact, that SW is not watching the changes of `#txt_base_frequency`. It should trigger `parseTuningData()`

**Comment by SeanArchibald** [comment]
We must have fixed this one a long while ago - I can see in the source that SW will trigger `parseTuningData()` when `#txt_base_frequency` is changed. The behaviour in the latest dev version is working as expected for me. Going to close this one for now but please re-open it if there is still any issue!
